name: Deploy to EC2

# 트리거 조건
# main 브랜치에 갱신되었을때 만 해당 워크플로우가 동작함
on:
  push:
    branches:
      - main

# 실제 실행할 내용
# runs-on: 우분투 최신버전으로 실행
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/ci-cd/ci-cd-example # EC2 인스턴스 내 프로젝트 경로로 진입
            git pull origin main # 코드 최신화
            npm install
            npm run build
            pm2 reload npm # PM2로 재실행
            echo "Deployment successful!"
